---
- name: Add a tag to EC2 instances with the ManagedBy=Ansible tag
  hosts: all
  gather_facts: false
  tasks:
    - name: Find instances with the ManagedBy=Ansible tag
      ec2_instance_facts:
        region: eu-west-1
        filters:
          "tag:ManagedBy": "Ansible"
      register: ec2_instances

    - name: Add a tag to the instances
      ec2_tag:
        region: eu-west-1
        resource: "{{ item.id }}"
        state: present
        tags:
          Vodafone: AnZ
      loop: "{{ ec2_instances.instances }}"

    - name: Ensure Ansible Tower has access to SSH private key
      copy:
        src: /home/ec2-user/terraform-aws/EU_WEST_WebSvcsDev.pem
        dest: /home/ansible/.ssh/key.pem
        mode: 0600
        owner: ansible
        group: ansible

    - name: Add EC2 instance to known hosts
      known_hosts:
        name: "{{ item.public_ip }}"
        key: "{{ item.key_name }}"
        keyfile: /home/ansible/.ssh/key.pem
        user: ansible
      loop: "{{ ec2_instances.instances }}"
